/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedWashingRouteImport } from './routes/_authenticated.washing'
import { Route as AuthenticatedMasterDataRouteImport } from './routes/_authenticated.master-data'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedFinancialsRouteImport } from './routes/_authenticated.financials'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWashingRoute = AuthenticatedWashingRouteImport.update({
  id: '/washing',
  path: '/washing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterDataRoute = AuthenticatedMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancialsRoute = AuthenticatedFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/washing': typeof AuthenticatedWashingRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/washing': typeof AuthenticatedWashingRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/financials': typeof AuthenticatedFinancialsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/master-data': typeof AuthenticatedMasterDataRoute
  '/_authenticated/washing': typeof AuthenticatedWashingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/financials'
    | '/home'
    | '/master-data'
    | '/washing'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/financials' | '/home' | '/master-data' | '/washing' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/financials'
    | '/_authenticated/home'
    | '/_authenticated/master-data'
    | '/_authenticated/washing'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/washing': {
      id: '/_authenticated/washing'
      path: '/washing'
      fullPath: '/washing'
      preLoaderRoute: typeof AuthenticatedWashingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master-data': {
      id: '/_authenticated/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof AuthenticatedMasterDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials': {
      id: '/_authenticated/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AuthenticatedFinancialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFinancialsRoute: typeof AuthenticatedFinancialsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMasterDataRoute: typeof AuthenticatedMasterDataRoute
  AuthenticatedWashingRoute: typeof AuthenticatedWashingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFinancialsRoute: AuthenticatedFinancialsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMasterDataRoute: AuthenticatedMasterDataRoute,
  AuthenticatedWashingRoute: AuthenticatedWashingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
