/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedWashingRouteImport } from './routes/_authenticated.washing'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedMasterDataRouteImport } from './routes/_authenticated.master-data'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedFinancialsRouteImport } from './routes/_authenticated.financials'
import { Route as AuthenticatedMasterDataIndexRouteImport } from './routes/_authenticated.master-data.index'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated.users.new'
import { Route as AuthenticatedMasterDataWashTypeRouteImport } from './routes/_authenticated.master-data.wash-type'
import { Route as AuthenticatedMasterDataGeneralCostRouteImport } from './routes/_authenticated.master-data.general-cost'
import { Route as AuthenticatedMasterDataCompanyRouteImport } from './routes/_authenticated.master-data.company'
import { Route as AuthenticatedUsersEditUserIdRouteImport } from './routes/_authenticated.users.edit.$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWashingRoute = AuthenticatedWashingRouteImport.update({
  id: '/washing',
  path: '/washing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterDataRoute = AuthenticatedMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancialsRoute = AuthenticatedFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterDataIndexRoute =
  AuthenticatedMasterDataIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMasterDataRoute,
  } as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedMasterDataWashTypeRoute =
  AuthenticatedMasterDataWashTypeRouteImport.update({
    id: '/wash-type',
    path: '/wash-type',
    getParentRoute: () => AuthenticatedMasterDataRoute,
  } as any)
const AuthenticatedMasterDataGeneralCostRoute =
  AuthenticatedMasterDataGeneralCostRouteImport.update({
    id: '/general-cost',
    path: '/general-cost',
    getParentRoute: () => AuthenticatedMasterDataRoute,
  } as any)
const AuthenticatedMasterDataCompanyRoute =
  AuthenticatedMasterDataCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedMasterDataRoute,
  } as any)
const AuthenticatedUsersEditUserIdRoute =
  AuthenticatedUsersEditUserIdRouteImport.update({
    id: '/edit/$userId',
    path: '/edit/$userId',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/master-data': typeof AuthenticatedMasterDataRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/washing': typeof AuthenticatedWashingRoute
  '/master-data/company': typeof AuthenticatedMasterDataCompanyRoute
  '/master-data/general-cost': typeof AuthenticatedMasterDataGeneralCostRoute
  '/master-data/wash-type': typeof AuthenticatedMasterDataWashTypeRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/master-data/': typeof AuthenticatedMasterDataIndexRoute
  '/users/edit/$userId': typeof AuthenticatedUsersEditUserIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/washing': typeof AuthenticatedWashingRoute
  '/': typeof AuthenticatedIndexRoute
  '/master-data/company': typeof AuthenticatedMasterDataCompanyRoute
  '/master-data/general-cost': typeof AuthenticatedMasterDataGeneralCostRoute
  '/master-data/wash-type': typeof AuthenticatedMasterDataWashTypeRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/master-data': typeof AuthenticatedMasterDataIndexRoute
  '/users/edit/$userId': typeof AuthenticatedUsersEditUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/financials': typeof AuthenticatedFinancialsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/master-data': typeof AuthenticatedMasterDataRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/washing': typeof AuthenticatedWashingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/master-data/company': typeof AuthenticatedMasterDataCompanyRoute
  '/_authenticated/master-data/general-cost': typeof AuthenticatedMasterDataGeneralCostRoute
  '/_authenticated/master-data/wash-type': typeof AuthenticatedMasterDataWashTypeRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/master-data/': typeof AuthenticatedMasterDataIndexRoute
  '/_authenticated/users/edit/$userId': typeof AuthenticatedUsersEditUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/financials'
    | '/home'
    | '/master-data'
    | '/users'
    | '/washing'
    | '/master-data/company'
    | '/master-data/general-cost'
    | '/master-data/wash-type'
    | '/users/new'
    | '/master-data/'
    | '/users/edit/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/financials'
    | '/home'
    | '/users'
    | '/washing'
    | '/'
    | '/master-data/company'
    | '/master-data/general-cost'
    | '/master-data/wash-type'
    | '/users/new'
    | '/master-data'
    | '/users/edit/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/financials'
    | '/_authenticated/home'
    | '/_authenticated/master-data'
    | '/_authenticated/users'
    | '/_authenticated/washing'
    | '/_authenticated/'
    | '/_authenticated/master-data/company'
    | '/_authenticated/master-data/general-cost'
    | '/_authenticated/master-data/wash-type'
    | '/_authenticated/users/new'
    | '/_authenticated/master-data/'
    | '/_authenticated/users/edit/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/washing': {
      id: '/_authenticated/washing'
      path: '/washing'
      fullPath: '/washing'
      preLoaderRoute: typeof AuthenticatedWashingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master-data': {
      id: '/_authenticated/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof AuthenticatedMasterDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials': {
      id: '/_authenticated/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AuthenticatedFinancialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master-data/': {
      id: '/_authenticated/master-data/'
      path: '/'
      fullPath: '/master-data/'
      preLoaderRoute: typeof AuthenticatedMasterDataIndexRouteImport
      parentRoute: typeof AuthenticatedMasterDataRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/master-data/wash-type': {
      id: '/_authenticated/master-data/wash-type'
      path: '/wash-type'
      fullPath: '/master-data/wash-type'
      preLoaderRoute: typeof AuthenticatedMasterDataWashTypeRouteImport
      parentRoute: typeof AuthenticatedMasterDataRoute
    }
    '/_authenticated/master-data/general-cost': {
      id: '/_authenticated/master-data/general-cost'
      path: '/general-cost'
      fullPath: '/master-data/general-cost'
      preLoaderRoute: typeof AuthenticatedMasterDataGeneralCostRouteImport
      parentRoute: typeof AuthenticatedMasterDataRoute
    }
    '/_authenticated/master-data/company': {
      id: '/_authenticated/master-data/company'
      path: '/company'
      fullPath: '/master-data/company'
      preLoaderRoute: typeof AuthenticatedMasterDataCompanyRouteImport
      parentRoute: typeof AuthenticatedMasterDataRoute
    }
    '/_authenticated/users/edit/$userId': {
      id: '/_authenticated/users/edit/$userId'
      path: '/edit/$userId'
      fullPath: '/users/edit/$userId'
      preLoaderRoute: typeof AuthenticatedUsersEditUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
  }
}

interface AuthenticatedMasterDataRouteChildren {
  AuthenticatedMasterDataCompanyRoute: typeof AuthenticatedMasterDataCompanyRoute
  AuthenticatedMasterDataGeneralCostRoute: typeof AuthenticatedMasterDataGeneralCostRoute
  AuthenticatedMasterDataWashTypeRoute: typeof AuthenticatedMasterDataWashTypeRoute
  AuthenticatedMasterDataIndexRoute: typeof AuthenticatedMasterDataIndexRoute
}

const AuthenticatedMasterDataRouteChildren: AuthenticatedMasterDataRouteChildren =
  {
    AuthenticatedMasterDataCompanyRoute: AuthenticatedMasterDataCompanyRoute,
    AuthenticatedMasterDataGeneralCostRoute:
      AuthenticatedMasterDataGeneralCostRoute,
    AuthenticatedMasterDataWashTypeRoute: AuthenticatedMasterDataWashTypeRoute,
    AuthenticatedMasterDataIndexRoute: AuthenticatedMasterDataIndexRoute,
  }

const AuthenticatedMasterDataRouteWithChildren =
  AuthenticatedMasterDataRoute._addFileChildren(
    AuthenticatedMasterDataRouteChildren,
  )

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedUsersEditUserIdRoute: typeof AuthenticatedUsersEditUserIdRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedUsersEditUserIdRoute: AuthenticatedUsersEditUserIdRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedFinancialsRoute: typeof AuthenticatedFinancialsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMasterDataRoute: typeof AuthenticatedMasterDataRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedWashingRoute: typeof AuthenticatedWashingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFinancialsRoute: AuthenticatedFinancialsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMasterDataRoute: AuthenticatedMasterDataRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedWashingRoute: AuthenticatedWashingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
